name: photo_manager_demo
description: "Photo manager demo for image pick"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  photo_manager: ^3.5.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  device_info_plus: ^10.1.2
  photo_manager_image_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
